name: monoids
baseurl: /monoids
description: Generic Monoids for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.2-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
